version:  '3.5'

networks:
  default:
    name: ${EXTERNAL_NET}

services:
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
        USER: ${USER}
        USER_NAME: ${USER_NAME}
        USER_EMAIL: ${USER_EMAIL}
        USER_ID: ${USER_ID}
        XDEBUG_CLIENT_PORT: ${XDEBUG_CLIENT_PORT}
    volumes:
      - ./app/:/var/www/app

  nginx:
    container_name: ${APP}
    image: nginx:1.23.3-alpine
    restart: on-failure
    volumes:
      - ./app/:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - app
